# Generated by Django 3.2.6 on 2021-08-20 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('gitlab_api_token', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100)),
                ('only_issues', models.BooleanField(verbose_name='Only issues')),
                ('only_milestones', models.BooleanField(verbose_name='Only milestones')),
                ('combined', models.BooleanField(default=False, verbose_name='Combined calendar')),
                ('reminder', models.FloatField(default=0, verbose_name='Reminder')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gitlabapi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
