# Generated by Django 3.2.6 on 2021-09-03 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('gitlab_api_token', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('write_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('projects', models.CharField(blank=True, default='', max_length=100, verbose_name='Project list')),
                ('groups', models.CharField(blank=True, default='', max_length=100, verbose_name='Group list')),
                ('config_name', models.CharField(max_length=100)),
                ('only_issues', models.BooleanField(default=False, verbose_name='Only issues')),
                ('only_milestones', models.BooleanField(default=False, verbose_name='Only milestones')),
                ('reminder', models.FloatField(default=0.0, verbose_name='Reminder')),
                ('file_exists', models.BooleanField(default=False, editable=False)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='core.gitlabapi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cal_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
