# Generated by Django 3.2.6 on 2021-08-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconfiguration',
            name='groups',
            field=models.CharField(default='', max_length=100, verbose_name='Group list'),
        ),
        migrations.AddField(
            model_name='calendarconfiguration',
            name='projects',
            field=models.CharField(default='', max_length=100, verbose_name='Project list'),
        ),
        migrations.AlterField(
            model_name='calendarconfiguration',
            name='only_issues',
            field=models.BooleanField(default=False, verbose_name='Only issues'),
        ),
        migrations.AlterField(
            model_name='calendarconfiguration',
            name='only_milestones',
            field=models.BooleanField(default=False, verbose_name='Only milestones'),
        ),
        migrations.AlterField(
            model_name='gitlabapi',
            name='gitlab_api_token',
            field=models.CharField(max_length=100),
        ),
    ]
